HTTP/1.1 403 Forbidden
X-Powered-By: Express
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Methods: GET,POST,PATCH,OPTIONS
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 37
ETag: W/"25-/UohQ78PfLPj1fT0eIrUgFVmT6U"
Date: Thu, 23 Jul 2026 13:49:55 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"message":"권한이 없습니다."}
