HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Methods: GET,POST,PATCH,OPTIONS
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 163
ETag: W/"a3-v0d+lha7jt1HNaXYFYvWCywAgZI"
Date: Thu, 23 Jul 2026 13:48:29 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"token":"0832bae1-9bd9-478f-994b-796289680361","user":{"id":"user-admin","name":"관리자","email":"admin@aivle.com","role":"ADMIN","approvalStatus":"APPROVED"}}
