HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Methods: GET,POST,PATCH,OPTIONS
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 213
ETag: W/"d5-+uwIvsa0wxEl2s/uS1ydXViGnRs"
Date: Thu, 23 Jul 2026 13:48:30 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"token":"08566799-54b1-4237-a45f-2d1e2d878e40","user":{"id":"user-supervisor","name":"김관리자","email":"supervisor@aivle.com","role":"MANAGER","approvalStatus":"APPROVED","organizationIds":["org-aivle-cs"]}}
