HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Methods: GET,POST,PATCH,OPTIONS
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 308
ETag: W/"134-/sy3oySlcO4tcdZj44EfKg83cFA"
Date: Thu, 23 Jul 2026 13:49:24 GMT
Connection: keep-alive
Keep-Alive: timeout=5

[{"id":"exam-2026-second-half","title":"2026년 하반기 신입 공채 AI 리터러시 역량 평가","category":"정규 평가 (Python / Java / C++)","duration":"90분","questions":"총 4문제","status":"AVAILABLE","date":"2026.07.20 ~ 2026.07.22","organizationName":"전체 플랫폼","questionCount":0}]
