HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Methods: GET,POST,PATCH,OPTIONS
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 206
ETag: W/"ce-ubGtkRWEu9Su09Tg2tnCy6F6xSk"
Date: Thu, 23 Jul 2026 13:49:24 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"id":"org-data-lab","name":"B대학교 데이터사이언스센터","code":"B-DATA","status":"APPROVED","requestedBy":"user-supervisor","managerIds":[],"createdAt":"2026-07-22T09:00:00.000Z","managers":[]}
