HTTP/1.1 201 Created
X-Powered-By: Express
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Methods: GET,POST,PATCH,OPTIONS
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 226
ETag: W/"e2-1FIS6EjGCkXp7HTBlKFMH8pV/3U"
Date: Thu, 23 Jul 2026 13:49:24 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"id":"41ac4ad9-4513-4d31-8d33-7c2f0d04d409","title":"QA 초대 링크 시험","duration":"30분","questions":"1문제","date":"2026-07-24 10:00","category":"정규 평가","status":"AVAILABLE","organizationId":"org-aivle-cs"}
