HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Methods: GET,POST,PATCH,OPTIONS
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 133
ETag: W/"85-v4CsQ5d8cPNK/OMiE1hsbLNkP+E"
Date: Thu, 23 Jul 2026 13:49:25 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"accessToken":"3ed4827d-df4a-4c51-99dc-3affbee47692","examId":"41ac4ad9-4513-4d31-8d33-7c2f0d04d409","candidateNumber":"AIVLE-1001"}
