HTTP/1.1 201 Created
X-Powered-By: Express
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Methods: GET,POST,PATCH,OPTIONS
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 441
ETag: W/"1b9-sqAwlEvhWJ7pvRoBi1aBqSrDeys"
Date: Thu, 23 Jul 2026 13:49:24 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"count":1,"deliveryStatus":"PREVIEW","mailPreviews":[{"to":"applicant1@aivle.com","examName":"QA 초대 링크 시험","schedule":"2026-07-24 10:00","entryLink":"http://localhost:5173/invite/46d89251-6fed-454e-8b8b-6654e8bc483a","candidateNumber":"AIVLE-1001","notice":"시험 시작 전 웹캠, 마이크, 화면 공유를 점검해주세요.","expiresAt":"2026-07-24T13:49:24.976Z","oneTimeToken":"46d89251-6fed-454e-8b8b-6654e8bc483a"}]}
